openapi: "3.0.1"
info:
  title: "lanchonete-apigateway-ENV_ENVIRONMENT"
  version: "2023-11-08T05:56:38Z"
servers:
- url: "https://0v0ejb40t3.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "ENV_ENVIRONMENT"
paths:
  /{proxy+}:
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        schema:
          type: "string"
      x-amazon-apigateway-integration:
        httpMethod: "ANY"
        uri: "https://www.google.com/search?q=teste"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        type: "http_proxy"
components: {}
