swagger: "2.0"
info:
  description: API Gateway
  version: "2023-01-31T12:43:59Z"
  title: lanchonete-apigateway-stg
schemes:
  - https
paths:
  /api/health:
    get:
      description: Show status
      produces:
        - "text/html"
      responses:
        "200":
          description: "200 response"
          headers:
            Content-Type:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
            responseParameters:
              method.response.header.Content-Type: "'text/html'"
            responseTemplates:
              text/html: "Up"
        requestTemplates:
          application/json: '{"status": "Up"}'
        passthroughBehavior: "when_no_match"
        type: mock

  /api/login:
    post:
      tags:
        - users
      operationId: login
      summary: User Login
      parameters:
      - in: body
        name: requestBody
        required: true
        schema:
          type: object
          properties:
            cpf:
              type: string
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "ENV_AUTHORIZATION_LAMBDA_ARN"
        type: "aws_proxy"

