name: 📦🚀 [Production] Api Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  build-production:
    uses: ./.github/workflows/main.yaml
    with:
      app_env: "prod"
      aws_region: "us-east-1"
      api_gateway_name: "lanchonete-apigateway-prd"
      path_contract: api/api-gateway-definition.yml
      env_file: api/production.env
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
